- name : nginx install #our wish
  host : web #ip 
  become : yes #-b to becoe root user
  task : 
  -name : installing ingix #our wish
  ansible.builtin.package module:  #taken from google
   name : nginx #service to install and start
   state : present #google
   -name : staring nginx #our wish
   ansible.builtin.service module: #google
     name : nginx #service to restart
     state: started

   
  

   