- name : nginx install 
  host : web  
  become : yes 
  task : 
  -name : installing ingix 
  ansible.builtin.package module:  
   name : nginx 
   state : present 
   -name : staring nginx 
   ansible.builtin.service module: 
     name : nginx 
     state: started