- name : nginx install 
  hosts : web  
  become : yes 
  tasks : 
  - name : installing nginx 
  ansible.builtin.package:  
   name : nginx 
   state : present 
   -name : staring nginx 
   ansible.builtin.service: 
     name : nginx 
     state : started